### ISSUE TITLE
E2E Tests: Failing Resizing Test

### ISSUE THREAD

**Issue by swissspidy** [ampproject/amp-wp#3119]
Since yesterday the test for resizing a rotated text block is failing. Something in the environment has changed in a way that negatively affects the test, presumably the new Gutenberg release that also happened yesterday.

**Comment by swissspidy** [comment]
The following tests are failing:

https://github.com/ampproject/amp-wp/blob/7515ad11d4006f7716d916b5f44ddacd4fd748d5/tests/e2e/specs/stories-editor/resizing.js#L159-L184

Test result:

```
  ● Resizing › Rotated Text block › should change the top and left position correctly when resizing a rotated block: topRight

    expect(received).toStrictEqual(expected) // deep equality

    Expected: "5%"
    Received: "8.3%"

      162 | 
      163 | 			const { positionLeft, positionTop } = await getSelectedBlockPosition();
    > 164 | 			expect( positionLeft ).toStrictEqual( '5%' );
          | 			                       ^
      165 | 			expect( positionTop ).toStrictEqual( '10%' );
      166 | 		} );
      167 | 

      at Object.toStrictEqual (specs/stories-editor/resizing.js:164:27)

  ● Resizing › Rotated Text block › should change the top and left position correctly when resizing a rotated block: right

    expect(received).toStrictEqual(expected) // deep equality

    Expected: "5%"
    Received: "7.8%"

      171 | 
      172 | 			const { positionLeft, positionTop } = await getSelectedBlockPosition();
    > 173 | 			expect( positionLeft ).toStrictEqual( '5%' );
          | 			                       ^
      174 | 			expect( positionTop ).toStrictEqual( '10%' );
      175 | 		} );
      176 | 

      at Object.toStrictEqual (specs/stories-editor/resizing.js:173:27)

  ● Resizing › Rotated Text block › should change the top and left position correctly when resizing a rotated block: bottomRight

    expect(received).toStrictEqual(expected) // deep equality

    Expected: "5%"
    Received: "30.9%"

      180 | 
      181 | 			const { positionLeft, positionTop } = await getSelectedBlockPosition();
    > 182 | 			expect( positionLeft ).toStrictEqual( '5%' );
          | 			                       ^
      183 | 			expect( positionTop ).toStrictEqual( '10%' );
      184 | 		} );
      185 | 

      at Object.toStrictEqual (specs/stories-editor/resizing.js:182:27)
```

**Comment by swissspidy** [comment]
I ran the test a few times now in non-headless mode, and what I see in the editor looks like expected behavior 🤔
